# TEM detector library with their specifications, can be extended
DETECTOR_LIBRARY = {   
    'Gatan 80X Metro': {   'aliases': ['80x.*metro', '80x.*metr', 'metro'],
                           'binning': 1,
                           'description': 'Gatan 80X Metro direct electron '
                                          'detector',
                           'image_height': 2048,
                           'image_width': 2048,
                           'pixel_size': 5},
    'K2 IS': {   'aliases': ['k2(?!.*base)', '^k2$'],
                 'binning': 1,
                 'description': 'Gatan K2 IS direct electron detector',
                 'image_height': 3712,
                 'image_width': 3840,
                 'pixel_size': 5.0},
    'OneView IS': {   'aliases': ['oneview.*is', 'oneviewis'],
                    'binning': 1,
                    'description': 'Gatan OneView IS sCMOS camera',
                    'image_height': 4096,
                    'image_width': 4096,
                    'pixel_size': 15},
    'OneView': {   'aliases': ['oneview(?!.*is)', '^oneview$'],
                   'binning': 1,
                   'description': 'Gatan OneView sCMOS camera',
                   'image_height': 4096,
                   'image_width': 4096,
                   'pixel_size': 15},
    'Orius SC200D': {   'aliases': ['orius', 'sc200d'],
                        'binning': 1,
                        'description': 'Gatan Orius SC200D CCD camera',
                        'image_height': 2048,
                        'image_width': 2048,
                        'pixel_size': 7.4},
    'Ultrascan 4000': {   'aliases': ['ultrascan.*4000', 'us4000'],
                    'binning': 1,
                    'description': 'Gatan Ultrascan 4000 CCD camera',
                    'image_height': 4096,
                    'image_width': 4096,
                    'pixel_size': 15},
                    
    'Ultrascan 1000': {   'aliases': ['ultrascan.*1000', 'us1000'],
                    'binning': 1,
                    'description': 'Gatan Ultrascan 1000 CCD camera',
                    'image_height': 2048,
                    'image_width': 2048,
                    'pixel_size': 14},
                    
    'Ultrascan': {   'aliases': ['ultrascan(?!.*(1000|4000))', '^ultrascan$'],
                     'binning': 1,
                     'description': 'Gatan Ultrascan CCD camera (2k)',
                     'image_height': 2048,
                     'image_width': 2048,
                     'pixel_size': 14.0},
                     
    'K3 IS': {   'aliases': ['k3.*is', 'k3is', 'k3(?!.*base)', '^k3$'],
                    'binning': 1,
                    'description': 'Gatan K3 IS direct electron detector',
                    'image_height': 3456,
                    'image_width': 3456,
                    'pixel_size': 5},
                    
    'K3 Base': {   'aliases': ['k3.*base', 'k3base'],
                    'binning': 1,
                    'description': 'Gatan K3 Base direct electron detector',
                    'image_height': 3072,
                    'image_width': 4608,
                    'pixel_size': 5},
                    
    'Rio 16': {   'aliases': ['rio.*16', 'rio16', 'rio'],
                    'binning': 1,
                    'description': 'Gatan Rio CMOS camera 16 megapixels',
                    'image_height': 4096,
                    'image_width': 4096,
                    'pixel_size': 9},
                    
    'Rio 9': {   'aliases': ['rio.*9', 'rio9'],
                    'binning': 1,
                    'description': 'Gatan Rio CMOS camera 9 megapixels',
                    'image_height': 3072,
                    'image_width': 3072,
                    'pixel_size': 9},
                    
    'Rio 4': {   'aliases': ['rio.*4', 'rio4'],
                    'binning': 1,
                    'description': 'Gatan Rio CMOS camera 4 megapixels',
                    'image_height': 2048,
                    'image_width': 2048,
                    'pixel_size': 9},
                    
    'ClearView': {   'aliases': ['clearview'],
                    'binning': 1,
                    'description': 'Gatan ClearView high-performance scintillator camera',
                    'image_height': 4096,
                    'image_width': 4096,
                    'pixel_size': 9},
                    
    'Alpine': {   'aliases': ['alpine'],
                    'binning': 1,
                    'description': 'Gatan Alpine direct detection camera',
                    'image_height': 3072,
                    'image_width': 4608,
                    'pixel_size': 5},
                    
    'Alpine Vista': {   'aliases': ['alpine.*vista', 'alpinevista'],
                    'binning': 1,
                    'description': 'Gatan Alpine Vista direct detection camera',
                    'image_height': 4092,
                    'image_width': 5760,
                    'pixel_size': 5},
                    
    'Metro': {   'aliases': ['metro(?!.*300)'],
                    'binning': 1,
                    'description': 'Gatan Metro in-situ counting camera (60-200 kV)',
                    'image_height': 2048,
                    'image_width': 2048,
                    'pixel_size': 5},
                    
    'Metro 300': {   'aliases': ['metro.*300', 'metro300'],
                    'binning': 1,
                    'description': 'Gatan Metro 300 in-situ counting camera (120-300 kV)',
                    'image_height': 2048,
                    'image_width': 2048,
                    'pixel_size': 5},
                    
    'Stela': {   'aliases': ['stela'],
                    'binning': 1,
                    'description': 'Gatan Stela hybrid-pixel camera',
                    'image_height': 512,
                    'image_width': 512,
                    'pixel_size': 55},
                    
    'Orius SC1000': {   'aliases': ['orius.*sc1000', 'sc1000'],
                    'binning': 1,
                    'description': 'Gatan Orius SC1000 CCD camera',
                    'image_height': 4008,
                    'image_width': 2672,
                    'pixel_size': 9},
                    
    'Orius SC600': {   'aliases': ['orius.*sc600', 'sc600'],
                    'binning': 1,
                    'description': 'Gatan Orius SC600 CCD camera',
                    'image_height': 2672,
                    'image_width': 2672,
                    'pixel_size': 9},
                    
    'OneView IS': {   'aliases': ['oneview.*is', 'oneviewis'],
                    'binning': 1,
                    'description': 'Gatan OneView IS sCMOS camera',
                    'image_height': 4096,
                    'image_width': 4096,
                    'pixel_size': 15},
                    
                    }